### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by semmy2010** [crazycodeboy/react-native-splash-screen#153]
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{20a557a3 V.E..... R....... 0,0-1080,1920} not attached to window manager 							
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:416) 							
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:342) 							
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:121) 							
	at android.app.Dialog.dismissDialog(Dialog.java:354) 							
	at android.app.Dialog.dismiss(Dialog.java:337) 							
	at org.devio.rn.splashscreen.SplashScreen$2.run(SplashScreen.java:66) 							
	at android.os.Handler.handleCallback(Handler.java:815) 							
	at android.os.Handler.dispatchMessage(Handler.java:104) 							
	at android.os.Looper.loop(Looper.java:194)  							
	at android.app.ActivityThread.main(ActivityThread.java:5714) 							
	at java.lang.reflect.Method.invoke(Native Method) 							
	at java.lang.reflect.Method.invoke(Method.java:372) 							
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 							
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by marcioadr88** [comment]
I have the same error:

```
java.lang.IllegalArgumentException: 
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:448)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:372)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:116)
  at android.app.Dialog.dismissDialog (Dialog.java:385)
  at android.app.Dialog.dismiss (Dialog.java:364)
  at org.devio.rn.splashscreen.SplashScreen$2.run (SplashScreen.java:66)
  at android.os.Handler.handleCallback (Handler.java:815)
  at android.os.Handler.dispatchMessage (Handler.java:104)
  at android.os.Looper.loop (Looper.java:207)
  at android.app.ActivityThread.main (ActivityThread.java:5765)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)
```

**Comment by lavaxun** [comment]
I'm also running into the same problem.

```
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:402)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:328)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:84)
  at android.app.Dialog.dismissDialog (Dialog.java:431)
  at android.app.Dialog.dismiss (Dialog.java:414)
  at org.devio.rn.splashscreen.SplashScreen$2.run (SplashScreen.java:66)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:5938)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1389)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1184)
```

**Comment by dprevost-LMI** [comment]
Same:
"@types/react-native": "0.67.4",
"react-native-splash-screen": "3.2.0",

We have that on a daily basis on Android only. 885 crashes in the last 30 days, and 43 in the last 24 hours.

java.lang.IllegalArgumentException: View=DecorView@a21d4ab[MainActivity] not attached to window manager
    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:563)
    at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:465)
    at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:141)
    at android.app.Dialog.dismissDialog(Dialog.java:473)
    at android.app.Dialog.dismiss(Dialog.java:455)
    at org.devio.rn.splashscreen.SplashScreen$2.run(SplashScreen.java:85)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7615)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

The line at org.devio.rn.splashscreen.SplashScreen$2.run(SplashScreen.java:85) is the `dismiss()` in the run of the hide method like below :
```java
            public void run() {
                if (mSplashDialog != null && mSplashDialog.isShowing()) {
                    boolean isDestroyed = false;

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                        isDestroyed = _activity.isDestroyed();
                    }

                    if (!_activity.isFinishing() && !isDestroyed) {
                        mSplashDialog.dismiss();
                    }
                    mSplashDialog = null;
                }
            }
```
Note: In our code, we often switch between two activities and the problem occurs mostly when we are switching between the two (and/or when they are being closed/destroyed)
