### ISSUE TITLE
Android Crash: java.lang.UnsupportedOperationException: Can't convert value at index 35 to color: type=0x1 (SplashScreen.java)

### ISSUE THREAD

**Issue by wbattel4607** [crazycodeboy/react-native-splash-screen#182]
```
"react": "^16.2.0",
"react-native": "0.53.3",
"react-native-splash-screen": "^3.0.6"
```

App crashes on startup, with the following error:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{foobar/foobar.MainActivity}: java.lang.UnsupportedOperationException: Can't convert value at index 35 to color: type=0x1
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Caused by java.lang.UnsupportedOperationException: Can't convert value at index 35 to color: type=0x1
       at android.content.res.TypedArray.getColor(TypedArray.java:463)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2407)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2627)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:402)
       at android.app.Dialog.setContentView(Dialog.java:512)
       at org.devio.rn.splashscreen.SplashScreen$1.run(SplashScreen.java:32)
       at android.app.Activity.runOnUiThread(Activity.java:5866)
       at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:26)
       at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:47)
       at com.thundersource.hilight.android.MainActivity.onCreate(MainActivity.java:26)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by bingneef** [comment]
This fixed it for me: https://github.com/crazycodeboy/react-native-splash-screen/issues/143

**Comment by asinel** [comment]
Unfortunately it doesn't help and I have the same problem

**Comment by xchesh** [comment]
You can update component from github and use latest version.
`npm i https://github.com/crazycodeboy/react-native-splash-screen.git`
`yarn add https://github.com/crazycodeboy/react-native-splash-screen.git`
