### ISSUE TITLE
Failed run at android emulator SDK API 19(Kit Kat)

### ISSUE THREAD

**Issue by billysutomo** [crazycodeboy/react-native-splash-screen#184]
### expected behaviour
open app and showing splash screen

### actual behaviour
when open app, its instantly crash

### error message

```
03-17 09:58:40.953 3873-3873/com.com.jejakimani E/CrashlyticsCore: Failed to execute task.
                                                                   java.util.concurrent.TimeoutException
                                                                       at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                                       at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
                                                                       at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:311)
                                                                       at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:295)
                                                                       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:30)
                                                                       at com.google.firebase.crash.FirebaseCrash$zzc.uncaughtException(Unknown Source)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                       at dalvik.system.NativeStart.main(Native Method)
03-17 09:58:40.953 3873-3873/com.com.jejakimani E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.com.jejakimani, PID: 3873
                                                                  java.lang.NoClassDefFoundError: org.devio.rn.splashscreen.SplashScreen$1
                                                                      at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:26)
                                                                      at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:47)
                                                                      at com.com.jejakimani.MainActivity.onCreate(MainActivity.java:19)
                                                                      at android.app.Activity.performCreate(Activity.java:5231)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                      at dalvik.system.NativeStart.main(Native Method)

```

### spec
react: 16.2.0
react-native: 0.53.3
react-native-splash-screen: 3.0.6

Im running the app on android emulator SDK API 19 (Kit Kat)

**Comment by timt** [comment]
I have the same problem (same versions)

Looks like a reoccurrence of #102 but the workaround of adding "primary_dark" to the colors.xml doesn't work

**Comment by Navindu09** [comment]
I am getting the same error, when the user logs out. Strange. Anyone know the solution?

**Comment by vijaykholiya** [comment]
Did anyone managed to resolve this error. Please help!
