### ISSUE TITLE
Linking failed RN 0.57.1

### ISSUE THREAD

**Issue by brightsider** [crazycodeboy/react-native-splash-screen#310]
```
rnpm-install info Linking react-native-splash-screen ios dependency
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'match' of undefined

TypeError: Cannot read property 'match' of undefined
    at findLineToAddPod (/node_modules/react-native/local-cli/link/pods/findLineToAddPod.js:22:17)
    at getLinesToAddEntry (/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:36:12)
    at registerNativeModulePods (/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:25:27)
    at Object.registerNativeModule [as register] (/node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:13:5)
    at Object.keys.forEach.platform (/node_modules/react-native/local-cli/link/link.js:74:16)
    at Array.forEach (<anonymous>)
    at linkDependency (/node_modules/react-native/local-cli/link/link.js:44:32)
    at <anonymous>
```

**Comment by brightsider** [comment]
No. Which package should be in Podfile for successful linking?

**Comment by ishigamii** [comment]
@brightsider I did the linking of this lib with my project in RN0.57.1 and nothing wrong happened so must be something with your configuration.

**Comment by RafaelFeiten** [comment]
I have the splash installed on other projects without the use of iOS pods, but I can't link it in this project with pod.
Someone running?
