### ISSUE TITLE
is supported "react-native": "^0.59.8"

### ISSUE THREAD

**Issue by lmr520** [crazycodeboy/react-native-splash-screen#391]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?

What platform does your issue occur on? (Android/iOS/Both)

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using?

**Comment by lmr520** [comment]
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `_wrapObjectFreezeAndFriends` from `E:\react\RN\ngcust\node_modules\react-native\Libraries\Core\polyfillES6Collections.js`: Module `_wrapObjectFreezeAndFriends` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (E:\react\RN\ngcust\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (E:\react\RN\ngcust\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\react\RN\ngcust\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (E:\react\RN\ngcust\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (E:\react\RN\ngcust\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)

**Comment by lmr520** [comment]
now I can see splash,but cant to app ,when do   SplashScreen.hide(); jump up this erro
