### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by leishi8819** [crazycodeboy/react-native-splash-screen#56]
日志捕获在SplashScreen.java:58行报错
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{3edec30a V.E..... R....... 0,0-1080,1920} not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:399)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:325)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
at android.app.Dialog.dismissDialog(Dialog.java:341)
at android.app.Dialog.dismiss(Dialog.java:324)
at com.cboy.rn.splashscreen.SplashScreen$2.run(SplashScreen.java:58)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5556)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by nikolay-radkov** [comment]
@leishi8819 I got the same error, did you find out what is causing it and how to prevent it?

**Comment by BenBach** [comment]
@nikolay-radkov We have the same issue. Did you find out the reason?

**Comment by nikolay-radkov** [comment]
No, we didn't find a solution.

**Comment by kr-atul** [comment]
@nikolay-radkov can we try putting [this](https://github.com/crazycodeboy/react-native-splash-screen/blob/b47197626804a742b8569cad50d5e0ed92fc765c/android/src/main/java/org/devio/rn/splashscreen/SplashScreen.java#L88) block into try catch? this is creating a lot of crashes.
<img width="1331" alt="Screenshot 2022-09-06 at 9 57 49 AM" src="https://user-images.githubusercontent.com/81958619/188547036-79928c39-43b2-4a5d-a64f-10d5549a8d82.png">
