### ISSUE TITLE
WeakReference NullPointerException

### ISSUE THREAD

**Issue by zxyah** [crazycodeboy/react-native-splash-screen#57]
``` java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
	at com.cboy.rn.splashscreen.SplashScreen.hide(SplashScreen.java:51)
	at com.cboy.rn.splashscreen.SplashScreenModule.hide(SplashScreenModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:207)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by dotansimha** [comment]
@crazycodeboy any idea?

**Comment by Shinichi52** [comment]
hi,
I has same issue

**Comment by mehdijjz** [comment]
I have the same issue and it's critical

**Comment by renso3x** [comment]
Is there no fix for this?
