### ISSUE TITLE
Splashscreen doesn't hide when upgraded to React Native 0.76

### ISSUE THREAD

**Issue by plindsay** [crazycodeboy/react-native-splash-screen#658]
Run `react-native info` in your project and share the content.

System:
  OS: macOS 15.0.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 96.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.6.1
    path: ~/.nvm/versions/node/v20.6.1/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v20.6.1/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/phil/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/phil/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0-alpha.2
    wanted: 15.0.0-alpha.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.0
    wanted: 0.76.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

What `react-native-splash-screen` version are you using?

3.3.0

What platform does your issue occur on? (Android/iOS/Both)

iOS

Describe your issue as precisely as possible : 

The app builds fine but just hangs on the splash screen.

**Comment by DevAsrar** [comment]
getting same issue, once the app is run i can not see the spalsh screen even it is not hiding too!

**Comment by plindsay** [comment]
> getting same issue, once the app is run i can not see the spalsh screen even it is not hiding too!

Been trying to debug this - for me I don't think my App.js is even being loaded (console logs don't appear), so it's not even reaching the code to hide the SplashScreen. So this may not be a problem with SplashScreen at all...

**Comment by DevAsrar** [comment]
The splash showing black `#000` screen after launch, we can hide it forcefully from app.js, but the concern is splash screen showing black screen, don't know whyy !! Please make a do changes with for support of RN 0.76.1 !!

**Comment by abhayagrawal-fareye** [comment]
Facing same problem..

**Comment by zoobibackups** [comment]
Double splash show when app is upload then double splash even i put code of double splash but can't hide the double splash

**Comment by zoobibackups** [comment]
@StevePotter  Same issue on uploaded app but in release apk cannot show double splash just show on uploaded app

**Comment by KarinaOleynik** [comment]
The same.. Is there any decision?

**Comment by Ajithkumar2203** [comment]
Yes for me facing crash in dev and release mode

**For React native version** "react-native": "^0.75.1"
Xcode Version 16.0
Mac os version 15.1
Build got crashed after the splash screen in testflight

In "react-native": "^0.76.1" 
Facing crash both dev and release mode after the splash screen

any one find the solution

**Comment by idylmz** [comment]
I had the same issue. In my case, it was about an error on my another library which it did not throw any exception. Just kept me waiting on splash screen.

In my case, wrongly imported SQLite functions was the main culprit. Turns out there was nothing wrong with my splash screen. I suggest you to put console.logs step by step to see your side of problems.

**Comment by frArdouin** [comment]
Same issue here. Just update to RN 0.76.3 and the app crash at the splash screen.

**Comment by tdinckaya** [comment]
I upgraded to React Native version 0.76.3.
I’m using the latest version of react-native-splash-screen (3.2.0).
Both Hermes and newArch are enabled.
Here is the error I’m getting in the logcat output:

````
FATAL EXCEPTION: mqt_v_native
                                                                                                    Process: com.myApp, PID: 28129
                                                                                                    com.facebook.react.common.JavascriptException: Error: Tried to access NativeModule "SplashScreen" from the bridge. This isn't allowed in Bridgeless mode., stack:
                                                                                                    anonymous@1:1105990
                                                                                                    loadModuleImplementation@1:102173
                                                                                                    guardedLoadModule@1:101696
                                                                                                    metroRequire@1:101326
                                                                                                    anonymous@1:732032
                                                                                                    loadModuleImplementation@1:102173
                                                                                                    guardedLoadModule@1:101696
                                                                                                    metroRequire@1:101326
                                                                                                    anonymous@1:108121
                                                                                                    loadModuleImplementation@1:102173
                                                                                                    guardedLoadModule@1:101653
                                                                                                    metroRequire@1:101326
                                                                                                    global@1:100871
                                                                                                    
                                                                                                    	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.kt:52)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
````

**Comment by rukmanary** [comment]
have you tried this https://github.com/crazycodeboy/react-native-splash-screen/issues/637#issuecomment-1922781411 ? I'm using RN 0.76.3 and its work fine at least on iOS. I don't know about Android because I still figure it out how to integrate with kotlin

**Comment by priyankgandhi0** [comment]
> have you tried this [#637 (comment)](https://github.com/crazycodeboy/react-native-splash-screen/issues/637#issuecomment-1922781411) ? I'm using RN 0.76.3 and its work fine at least on iOS. I don't know about Android because I still figure it out how to integrate with kotlin

In my case, when i adding [RNSplashScreen show]; to my AppDelegate.mm file, then my app gets stuck on the splash screen in ios.

This solution work for me as well. Thanks!

**Comment by Piyush-Manglani** [comment]
> have you tried this [#637 (comment)](https://github.com/crazycodeboy/react-native-splash-screen/issues/637#issuecomment-1922781411) ? I'm using RN 0.76.3 and its work fine at least on iOS. I don't know about Android because I still figure it out how to integrate with kotlin

Thanks @rukmanary , this solution is working for IOS.

did you get any solution for android ? In android getting Cannot read property 'hide' of null

**Comment by taongocson** [comment]
react native > 0.7x.x
add  key into file Info.plist

```
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
```

**Comment by rupal-syngenta** [comment]
Facing same issue

**Comment by jagnesh** [comment]
🚀 **Consider Using `react-native-splash-view` Instead!**  

Hey there! 👋 If you're facing issues with `AppDelegate` changes in React Native 0.76+, you might want to try **[`[react-native-splash-view]`](https://www.npmjs.com/package/react-native-splash-view)** instead!  

✅ **Why switch to `react-native-splash-view`?**  
- Fully compatible with **React Native 0.76+**, including **Swift-based AppDelegate**.  
- No extra hassle—**works smoothly with both Objective-C & Swift projects**.  
- **Simple integration** with iOS **storyboard splash screens** & Android **launch screens**.  
- Lightweight & actively maintained for the latest React Native versions.  

Check it out & give it a try! 🚀✨
